name: todo_tracker
description: My TODOs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2

  cupertino_icons: ^1.0.0
  sembast: ^3.1.0+2
  json_annotation: ^4.0.0
  provider: ^5.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  uuid: ^3.0.4
  rxdart: ^0.27.1

dev_dependencies:
  json_serializable: ^4.0.2
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
